version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "3001:3001"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - "3002:3002"
  
  films:
    container_name: films
    restart: always
    build: ./films
    ports:
      - "3003:3003"

  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:
      - "3004:3004"

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - "3005:3005"