version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - "${CHARACTERS_PORT}:${CHARACTERS_PORT}"
  
  films:
    container_name: films
    restart: always
    build: ./films
    ports:
      - "${FILMS_PORT}:${FILMS_PORT}"

  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:
      - "${PLANETS_PORT}:${PLANETS_PORT}"

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"